version: '3'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:14.9-alpine3.18
    networks:
      - app-tier
    ports:
      - 5439:5439
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ccdn0koment
      - POSTGRES_PORT=5439
  app:
    restart: on-failure
    build: .
    networks:
      - app-tier
    depends_on:
      - postgres
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - .env-docker